name: lil_broc
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.3
  google_fonts: ^2.1.1
  animated_text_kit: ^4.2.1
  provider: ^6.0.3
  percent_indicator: ^4.0.1
  flutter_slidable: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  uuid: ^3.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/fruits_vegetables/

# * comando generar icons: flutter pub run flutter_launcher_icons:main
# Configs de flutter_launcher_icons para generar iconos
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
